### ISSUE TITLE
Unable to promisify localStorage

### ISSUE THREAD

**Issue by paras-ziggletech** [manuel-di-iorio/promisify-es6#3]
Hi,
I want to promisify the localStorage object.

using like this  -
const get = promisify(localStorage.getItem)

Can you tell me what i am doing wrong ?

Thank you

**Comment by manuel-di-iorio** [comment]
Hi @paras-ziggletech , localStorage functions are synchronus methods, so there is no need to promisify them.
Any function which accepts a **next** callback as latest argument, can be promisified.

Use case:
```javascript
await asyncFunction();
const value = localStorage.getItem("key");
// other calls here...
```
